### ISSUE TITLE
adminCheck function

### ISSUE THREAD

**Issue by JennaDalgety** [the-difference-engine/we-r-next-generation-web#52]
adminCheck function is seeming to have some issues.

- when I placed the ```beforeEnter: adminCheck`` on components in the index.js file, it would not load these components (triple-checked that URLs and routing were correct)
- I switched to ```beforeEnter: sessionCheck``` and was able to load the components.
- In particular, I was trying this with my successEdit component

Let me know if further info is needed.

**Comment by zachgarwood** [comment]
I looked into `adminCheck` and it's functionality is already incorporated into the related `sessionCheck`. So I'm going to remove it and any references to it.
